-- ===================================================================
-- Migration 008: Seed All Live Site Settings & Default Content
-- Ensures all public section keys exist in system_settings without
-- overwriting any existing custom edits made by administrators.
-- ===================================================================

INSERT INTO system_settings (setting_key, setting_value, description, group_name) VALUES
('org_name', 'Drodul Phendey Ling Foundation', 'Official registered name of the foundation', 'general'),
('org_tagline', 'Building Peace. Empowering Lives.', 'Official foundation motto', 'general'),
('org_address', 'Great Druk Wangyel Peace Stupa Complex, Gelephu, Sarpang Dzongkhag, Kingdom of Bhutan', 'Physical headquarters address', 'general'),
('org_phone', '+975 17556559', 'Primary contact phone number', 'general'),
('org_email', 'contact@drodulphendeyling.org', 'Public contact email address', 'general'),
('site_name', 'Drodul Phendey Ling Foundation', 'Website display brand title', 'general'),
('site_tagline', 'Building Peace. Empowering Lives.', 'Website display subtitle/tagline', 'general'),
('site_tibetan_name', '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པ།', 'Official Tibetan script title', 'general'),
('tibetan_title', '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པ།', 'Tibetan sacred title', 'general'),

-- Header & Announcement
('header_announcement', '☸ Welcoming Devotees to the Historic 108ft Great Druk Wangyel Peace Stupa • 80G Tax Exemption Available', 'Top announcement banner text', 'header'),
('header_announcement_on', 'true', 'Announcement banner visibility', 'header'),
('header_announcement_link', '/about', 'Announcement banner target link', 'header'),
('header_phone', '+975 17556559', 'Top bar contact telephone', 'header'),
('header_email', 'contact@drodulphendeyling.org', 'Top bar contact email', 'header'),
('header_location', 'Gelephu, Sarpang, Bhutan', 'Top bar location string', 'header'),
('header_cta_label', 'Offer Dana', 'Top navigation call to action label', 'header'),
('header_cta_link', '/donate', 'Top navigation call to action URL', 'header'),
('header_cta_on', 'true', 'Top CTA button visibility', 'header'),
('header_btn_text', 'Offer Dana', 'Top CTA button label', 'header'),
('header_btn_link', '/donate', 'Top CTA button URL', 'header'),

-- Homepage Hero
('home_hero_badge', '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པ། • Gelephu, Bhutan', 'Hero Tibetan inscription pill', 'home'),
('home_hero_title', 'BUILDING A SACRED LEGACY OF PEACE & WISDOM', 'Hero main title', 'home'),
('home_hero_subtitle', 'Constructing the monumental 108ft Great Druk Wangyel Peace Stupa, expanding the Shedra Monastic University, and preserving authentic Buddha Dharma for global harmony in Gelephu, Bhutan.', 'Hero mission subtitle', 'home'),
('home_hero_image', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1800&q=85', 'Hero background banner image URL', 'home'),
('home_hero_cta_text', 'OFFER DANA / DONATE', 'Hero primary CTA button text', 'home'),
('home_hero_cta_link', '/donate', 'Hero primary CTA target URL', 'home'),
('home_hero_cta2_text', 'Explore Stupa Vision', 'Hero secondary CTA button text', 'home'),
('home_hero_cta2_link', '/about', 'Hero secondary CTA target URL', 'home'),

-- Homepage Stats
('stat1_num', '108 Ft', 'Impact metric 1 counter value', 'stats'),
('stat1_label', 'Monumental Stupa', 'Impact metric 1 title', 'stats'),
('stat1_sub', 'Gelephu, Bhutan', 'Impact metric 1 subtitle', 'stats'),
('stat2_num', '350+', 'Impact metric 2 counter value', 'stats'),
('stat2_label', 'Monastic Scholars', 'Impact metric 2 title', 'stats'),
('stat2_sub', 'Shedra university scholars', 'Impact metric 2 subtitle', 'stats'),
('stat3_num', '100k+', 'Impact metric 3 counter value', 'stats'),
('stat3_label', 'Consecrated Prayers', 'Impact metric 3 title', 'stats'),
('stat3_sub', 'Sacred butter lamps', 'Impact metric 3 subtitle', 'stats'),
('stat4_num', '40+', 'Impact metric 4 counter value', 'stats'),
('stat4_label', 'Global Patronage', 'Impact metric 4 title', 'stats'),
('stat4_sub', 'International devotees', 'Impact metric 4 subtitle', 'stats'),

-- Homepage Campaigns
('campaigns_badge', 'Sacred Giving Initiatives', 'Campaigns section badge', 'campaigns'),
('campaigns_title', 'Support Our Active Monastic Projects', 'Campaigns section headline', 'campaigns'),
('campaigns_subtitle', 'Every contribution directly funds the 108ft Great Peace Stupa, provides meals and education for 350+ monks, and preserves living Buddha Dharma.', 'Campaigns subtitle', 'campaigns'),
('campaigns_cta_text', 'View All Giving Causes', 'Campaigns button text', 'campaigns'),
('campaigns_cta_link', '/donate', 'Campaigns button link', 'campaigns'),

-- Homepage Documentary
('doc_badge', 'Monastery Documentary Film', 'Documentary badge', 'documentary'),
('home_doc_badge', 'Monastery Documentary Film', 'Documentary badge fallback', 'documentary'),
('home_doc_title', 'The Sacred Legacy of Drodul Phendey Ling', 'Documentary heading', 'documentary'),
('doc_video_url', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'Documentary video embed URL', 'documentary'),
('home_doc_video_url', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'Documentary video embed URL fallback', 'documentary'),
('doc_poster_image', 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80', 'Documentary poster image', 'documentary'),
('home_doc_desc', 'Journey into the spiritual heart of Gelephu, Bhutan. Witness the devotion of our monastic community, the architectural wonder of the 108ft Peace Stupa, and the living wisdom of Tibetan Buddhism.', 'Documentary description', 'documentary'),
('doc_duration', '14 min documentary', 'Documentary duration pill', 'documentary'),
('doc_cta1_text', 'Watch Full Story', 'Documentary watch button', 'documentary'),
('doc_cta2_text', 'About Our Lineage', 'Documentary secondary button', 'documentary'),

-- Homepage Pillars
('home_pillars_badge', 'Four Sacred Pillars of Activity', 'Pillars badge', 'pillars'),
('home_pillars_title', 'Fulfilling the Bodhisattva Mandate', 'Pillars headline', 'pillars'),
('home_pillars_subtitle', 'Preserving Buddhist heritage through architectural monuments, philosophical inquiry, unbroken prayer dedications, and humanitarian sangha care.', 'Pillars subtitle', 'pillars'),
('home_pillar1_title', '108ft Great Peace Stupa', 'Pillar 1 title', 'pillars'),
('home_pillar1_badge', 'Architectural Stupa', 'Pillar 1 badge', 'pillars'),
('home_pillar1_desc', 'Constructing a landmark symbol of peace with 108 stone-carved prayer wheels and consecration relics.', 'Pillar 1 description', 'pillars'),
('home_pillar2_title', 'Shedra Monastic University', 'Pillar 2 title', 'pillars'),
('home_pillar2_badge', '9-Year Acharya', 'Pillar 2 badge', 'pillars'),
('home_pillar2_desc', 'Educating 350+ young monks in Buddhist philosophy, classical debate, linguistics, and Dharma meditation.', 'Pillar 2 description', 'pillars'),
('home_pillar3_title', 'Sacred Puja & Butter Lamps', 'Pillar 3 title', 'pillars'),
('home_pillar3_badge', 'Daily Consecration', 'Pillar 3 badge', 'pillars'),
('home_pillar3_desc', 'Perpetual prayers dedicated by resident monks for obstacle clearance, longevity, and world peace.', 'Pillar 3 description', 'pillars'),
('home_pillar4_title', 'Humanitarian Relief & Care', 'Pillar 4 title', 'pillars'),
('home_pillar4_badge', 'Sangha Care', 'Pillar 4 badge', 'pillars'),
('home_pillar4_desc', 'Providing daily vegetarian nutrition, medical treatment, robes, and community welfare across Gelephu.', 'Pillar 4 description', 'pillars'),

-- Homepage Prayers Callout
('home_prayers_badge', 'Consecrated Evening Rituals', 'Prayer callout badge', 'prayers'),
('home_prayers_title', 'Request Sacred Prayers & 108 Butter Lamps', 'Prayer callout heading', 'prayers'),
('home_prayers_subtitle', 'Submit personal prayer intentions and names of loved ones. Our resident Shedra monks chant consecrated prayers and illuminate 108 brass butter lamps in the holy shrine altar.', 'Prayer callout subtitle', 'prayers'),
('home_prayers_cta_text', 'Light a Butter Lamp', 'Prayer callout button text', 'prayers'),
('home_prayers_cta_link', '/prayer-request', 'Prayer callout button URL', 'prayers'),

-- Homepage About Narrative
('home_about_title', 'From Sacred Lineage to Global World Peace', 'About narrative title', 'about'),
('home_about_description', 'Nestled in the tranquil Himalayan foothills of Gelephu, Bhutan, Drodul Phendey Ling Foundation brings together revered Buddhist masters, dedicated monk scholars, and international patrons to preserve centuries-old Tibetan Buddhist heritage and complete the historic Great Druk Wangyel Peace Stupa.', 'About narrative description', 'about'),

-- About Page
('about_tibetan_eyebrow', '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པའི་ལོ་རྒྱུས། • Sacred Monastic Heritage', 'About header Tibetan eyebrow', 'about'),
('about_page_title', 'About Drodul Phendey Ling Foundation', 'About page title', 'about'),
('about_page_subtitle', 'Established in the tranquil Himalayan foothills of Gelephu, Sarpang Dzongkhag, Bhutan, to nurture authentic Buddha Dharma, train monk scholars, and build the historic 108ft Great Druk Wangyel Peace Stupa.', 'About page subtitle', 'about'),
('about_mandate_text', 'Founded under the spiritual patronage of venerable masters, our monastery serves as a beacon of Vajrayana wisdom, sheltering over 350 monks and leading humanitarian projects.', 'About mandate text', 'about'),
('about_pillars_tibetan', 'རྩ་བའི་དམིགས་ཡུལ་གསུམ།', 'About pillars Tibetan title', 'about'),
('about_pillars_title', 'Three Sacred Core Pillars', 'About pillars title', 'about'),
('about_pillars_intro', 'Our monastery guides activities through three noble focal points: authentic lineage preservation, rigorous monastic education, and compassionate humanitarian welfare.', 'About pillars intro', 'about'),
('about_pillar_1_title', 'Sacred Lineage & Vision', 'About pillar 1 title', 'about'),
('about_pillar_1_desc', 'Rooted in authentic Vajrayana and Mahayana traditions, our mission is to cultivate universal compassion, wisdom, and an enlightened sanctuary where monastic and lay practitioners realize inner peace.', 'About pillar 1 description', 'about'),
('about_pillar_2_title', 'Shedra Monastic University', 'About pillar 2 title', 'about'),
('about_pillar_2_desc', 'Providing 350+ enrolled monks with full residential scholarships, classical Tibetan linguistics, Abhidharma, Madhyamaka philosophy, debate epistemics, and contemplative solitary retreats.', 'About pillar 2 description', 'about'),
('about_pillar_3_title', 'Great Peace Stupa', 'About pillar 3 title', 'about'),
('about_pillar_3_desc', 'The monumental 108-foot Great Druk Wangyel Peace Stupa serves as a beacon of harmony, housing sacred relic chambers, 108 stone-carved prayer wheels, and pacifying discord for all beings.', 'About pillar 3 description', 'about'),
('about_leader_pill', 'Monastic Leadership', 'Leadership pill label', 'about'),
('about_leader_heading', 'Venerable Spiritual Guidance', 'Leadership heading', 'about'),
('about_leader_name', 'H.E. Khenpo Karma Rinpoche', 'Abbot name', 'about'),
('about_leader_title', 'Abbot & Principal of Shedra Academy', 'Abbot title', 'about'),
('about_leader_bio', 'Having completed nine years of rigorous Shedra curriculum and traditional solitary mountain retreat, Khenpo Rinpoche oversees the monastic training, sacred stupa construction, and philanthropic welfare programs in Gelephu, Bhutan.', 'Abbot bio', 'about'),
('about_leader_blessing', 'May every stone carved for this Stupa, every mantra chanted in this Shedra, bring peace to a troubled world.', 'Abbot blessing quote', 'about'),
('about_leader_image', 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80', 'Abbot portrait image URL', 'about'),
('about_leader_cta_text', 'Contact Abbot Office', 'Abbot contact button text', 'about'),
('about_leader_cta_link', '/contact', 'Abbot contact button URL', 'about'),
('about_statutory_badge', 'Official Accreditation', 'Statutory badge', 'about'),
('about_statutory_title', 'Statutory Trust & Accountability', 'Statutory title', 'about'),
('about_statutory_desc', 'Drodul Phendey Ling Foundation operates in strict accordance with the Religious Organizations Act of the Kingdom of Bhutan. Our accounts are audited annually by certified independent chartered accountants and submitted to statutory regulatory authorities.', 'Statutory description', 'about'),
('about_statutory_summary', 'Registered under the Commission for Religious Organizations (CRO) of Bhutan • Registration No: CRO/BTN/2026/049. All donations are 100% transparent and audited.', 'Statutory summary', 'about'),
('about_statutory_fcra', 'Approved for institutional cross-border wire transfers and statutory tax certification.', 'Statutory wire approval', 'about'),

-- Donation & Banking Details
('donate_hero_title', 'Make A Meritorious Offering for Peace & Buddha Dharma', 'Donate page hero title', 'donate'),
('donate_hero_subtitle', 'Every offering directly finances the 108ft Great Druk Wangyel Peace Stupa, sustains resident monks with nutrition and education, and radiates blessings of merit across the world.', 'Donate hero subtitle', 'donate'),
('donate_hero_badge', 'Charitable Giving • 80G Tax Exemption Available', 'Donate hero badge', 'donate'),
('donate_hero_image', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80', 'Donate hero banner image URL', 'donate'),
('donate_bank_title', 'Direct Bank Transfer / Wire Details', 'Bank wire title', 'donate'),
('donate_bank_subtitle', 'Devotees preferring direct RTGS, NEFT, or international SWIFT wire transfers may remit directly to our official institutional account:', 'Bank wire subtitle', 'donate'),
('bank_name', 'Bank of Bhutan Ltd. (BoB)', 'Bank name', 'banking'),
('bank_account_name', 'Drodul Phendey Ling Foundation', 'Bank account holder name', 'banking'),
('bank_account_no', '200847291038', 'Bank account number', 'banking'),
('bank_swift_code', 'BHUBBTBT', 'Bank SWIFT code', 'banking'),
('bank_branch', 'Gelephu Main Branch, Bhutan', 'Bank branch name', 'banking'),
('bank_ifsc', 'BOBB0000001', 'Bank IFSC / routing code', 'banking'),
('bank_upi_id', 'drodulphendeyling@bob', 'Monastery UPI ID', 'banking'),
('bank_qr_image', '', 'Monastery UPI QR code image URL', 'banking'),
('upi_merchant_vpa', 'drodulphendeyling@bob', 'Merchant UPI VPA', 'banking'),
('upi_merchant_name', 'Drodul Phendey Ling Foundation', 'Merchant UPI display name', 'banking'),
('donation_preset_amounts', '500, 1100, 2100, 5100, 11000', 'Preset offering buttons', 'donate'),
('donation_default_amount', '1100', 'Default selected donation amount', 'donate'),
('donate_presets_title', 'Sacred Offering Presets', 'Offering presets title', 'donate'),
('donate_presets_subtitle', 'Choose an auspicious offering amount. Each tier supports monastic essentials, ritual butter lamps, and stupa construction.', 'Offering presets subtitle', 'donate'),
('donate_presets_merit_note', 'Custom amounts are welcome. 80G tax receipt is issued automatically upon verification.', 'Presets merit note', 'donate'),
('donate_tier_1_amount', '500', 'Tier 1 offering amount', 'donate'),
('donate_tier_1_label', '21 Butter Lamps Puja', 'Tier 1 offering label', 'donate'),
('donate_tier_2_amount', '1100', 'Tier 2 offering amount', 'donate'),
('donate_tier_2_label', 'Daily Sangha Nutrition Fund', 'Tier 2 offering label', 'donate'),
('donate_tier_3_amount', '2100', 'Tier 3 offering amount', 'donate'),
('donate_tier_3_label', 'Monastic Robes & Healthcare', 'Tier 3 offering label', 'donate'),
('donate_tier_4_amount', '5100', 'Tier 4 offering amount', 'donate'),
('donate_tier_4_label', 'Shedra Study Scholarships', 'Tier 4 offering label', 'donate'),
('donate_tier_5_amount', '11000', 'Tier 5 offering amount', 'donate'),
('donate_tier_5_label', 'Peace Stupa Carved Stone', 'Tier 5 offering label', 'donate'),

-- Statutory Tax Details
('tax_exempt_title', 'Statutory Tax Exemption & Monastic Governance', 'Tax exemption section title', 'statutory'),
('tax_exempt_reg', 'DPL/TAX-EXEMPT/BTN/2026/80G-092', 'Tax exemption registration code', 'statutory'),
('tax_80g_order_no', 'CIT(E)/THIMPHU/80G/2026-27/AAATD1234F', 'Statutory 80G order number', 'statutory'),
('tax_exempt_authority', 'Commission for Religious Organizations (CRO), Kingdom of Bhutan', 'Exemption authority', 'statutory'),
('tax_exempt_clause', 'Section 80G Tax Deductible Charitable Contribution', 'Tax clause reference', 'statutory'),
('tax_exempt_percent', '100% Tax Deductible in Bhutan', 'Tax exemption percentage', 'statutory'),
('tax_exempt_timeline', 'Certified PDF money receipt issued immediately upon treasury verification.', 'Tax receipt timeline', 'statutory'),
('tax_exempt_email', 'finance@drodulphendeyling.org', 'Finance office email', 'statutory'),

-- Ceremonial Prayers
('prayer_tibetan_eyebrow', '༄༅། །མར་མེ་སྨོན་ལམ། • Consecrated Sangha Pujas & Butter Lamps', 'Prayer Tibetan eyebrow', 'prayers'),
('prayer_hero_title', 'Sacred Prayer Dedication & Offerings', 'Prayer page hero title', 'prayers'),
('prayer_hero_subtitle', 'Our resident monastic Sangha at Drodul Phendey Ling recites daily consecrated prayers and illuminates brass butter lamps before the holy altar for world peace, health, longevity, and obstacle clearance.', 'Prayer hero subtitle', 'prayers'),
('prayer_puja_heading', 'Daily Consecrated Monastic Pujas', 'Puja heading', 'prayers'),
('prayer_puja_1_title', 'Grand Tara Obstacle Clearance Puja (Drolma Chodpa)', 'Puja 1 title', 'prayers'),
('prayer_puja_1_desc', 'Chanting the 21 Praises to Tara for swift protection, spiritual clarity, and pacification of worldly difficulties.', 'Puja 1 description', 'prayers'),
('prayer_puja_2_title', 'Medicine Buddha Healing Puja (Menlha)', 'Puja 2 title', 'prayers'),
('prayer_puja_2_desc', 'Consecrated healing visualization and recitations dedicated to those experiencing illness, physical suffering, or surgery.', 'Puja 2 description', 'prayers'),
('prayer_lamp_badge', 'Perpetual Light Offering', 'Butter lamp badge', 'prayers'),
('prayer_lamp_title', '108 Sacred Butter Lamp Illuminations', 'Butter lamp title', 'prayers'),
('prayer_tier_1_count', '21', 'Lamp tier 1 count', 'prayers'),
('prayer_tier_1_amt', '500', 'Lamp tier 1 amount', 'prayers'),
('prayer_tier_2_count', '108', 'Lamp tier 2 count', 'prayers'),
('prayer_tier_2_amt', '1500', 'Lamp tier 2 amount', 'prayers'),
('prayer_schedule_title', 'Monastery Puja & Chanting Schedule', 'Puja schedule title', 'prayers'),
('prayer_schedule_desc', 'Our Sangha adheres to the ancient liturgical cycle with three consecrated recitation periods daily:', 'Puja schedule description', 'prayers'),
('prayer_schedule_morning', '05:30 AM - 07:00 AM (Dawn Tara & Sang Offering)', 'Puja schedule morning slot', 'prayers'),
('prayer_schedule_evening', '05:30 PM - 07:00 PM (Dusk Mahakala & Dharmapala Protector Ritual)', 'Puja schedule evening slot', 'prayers'),
('prayer_session_1_title', 'Dawn Tara Puja (Drolma Chodpa)', 'Session 1 title', 'prayers'),
('prayer_session_1_time', '05:30 AM - 07:00 AM', 'Session 1 time', 'prayers'),
('prayer_session_1_desc', 'Praising the 21 Taras for swift obstacle clearance, feminine wisdom, and family well-being.', 'Session 1 description', 'prayers'),
('prayer_session_2_title', 'Noon Medicine Buddha Healing Puja', 'Session 2 title', 'prayers'),
('prayer_session_2_time', '11:00 AM - 12:30 PM', 'Session 2 time', 'prayers'),
('prayer_session_2_desc', 'Consecrated chanting for recovery from illness, mental pacification, and compassionate healing.', 'Session 2 description', 'prayers'),
('prayer_session_3_title', 'Dusk Mahakala & Dharmapala Protector Ritual', 'Session 3 title', 'prayers'),
('prayer_session_3_time', '05:30 PM - 07:00 PM', 'Session 3 time', 'prayers'),
('prayer_session_3_desc', 'Dharmapala invocation and 108 butter lamp illuminations to dispel negative conditions and safeguard peace.', 'Session 3 description', 'prayers'),

-- Shedra Academy
('shedra_hero_badge', 'Center for Advanced Buddhist Epistemology & Scholastic Studies', 'Shedra hero badge', 'shedra'),
('shedra_hero_title', 'Drodul Phendey Ling Shedra Monastic Academy', 'Shedra hero title', 'shedra'),
('shedra_hero_subtitle', 'Rooted in the ancient Nalanda scholastic lineage of Bhutan, our Shedra trains monk scholars in the Five Great Treatises of Buddhist Philosophy over a rigorous 9-year Master of Buddhist Studies (Acharya) curriculum.', 'Shedra hero subtitle', 'shedra'),
('shedra_hero_image', 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80', 'Shedra hero image URL', 'shedra'),
('shedra_shastras_badge', 'Scholastic Heritage', 'Shastras badge', 'shedra'),
('shedra_shastras_title', 'The Five Great Shastras', 'Shastras title', 'shedra'),
('shedra_shastras_subtitle', 'Every monk scholar must master debate, textual translation, and meditation upon the five comprehensive pillars of classical Indian and Tibetan Buddhism.', 'Shastras subtitle', 'shedra'),
('shastra1_title', 'Pramanavarttika (Buddhist Epistemology & Logic)', 'Shastra 1 title', 'shedra'),
('shastra1_years', 'Years 1 - 2', 'Shastra 1 years', 'shedra'),
('shastra1_desc', 'Dharmakirti’s profound treatise on validity, reasoning, perception, and philosophical debate.', 'Shastra 1 description', 'shedra'),
('shastra2_title', 'Prajnaparamita (Perfection of Wisdom)', 'Shastra 2 title', 'shedra'),
('shastra2_years', 'Years 3 - 4', 'Shastra 2 years', 'shedra'),
('shastra2_desc', 'Maitreya and Asanga’s Abhisamayalankara exploring the stages and grounds of the Bodhisattva path.', 'Shastra 2 description', 'shedra'),
('shedra_fac_title', 'Monastic Study Facilities & Campus', 'Shedra facilities title', 'shedra'),
('shedra_fac_desc', 'Purpose-built Dharma classrooms, traditional open-air debate stone courtyards, extensive scripture library, and monk residential quarters in Gelephu.', 'Shedra facilities description', 'shedra'),
('shedra_fac_1_title', 'Debate Courtyard (Chora)', 'Facility 1 title', 'shedra'),
('shedra_fac_1_desc', 'Daily afternoon and evening dialectical debates cultivating sharp analytical mind and scriptural mastery.', 'Facility 1 description', 'shedra'),
('shedra_fac_2_title', 'Sacred Kangyur & Tengyur Library', 'Facility 2 title', 'shedra'),
('shedra_fac_2_desc', 'Housing over 300 volumes of canonical Buddhist treatises and classical Tibetan block prints.', 'Facility 2 description', 'shedra'),
('shedra_admit_pill', 'Join the Academy', 'Admissions pill label', 'shedra'),
('shedra_admit_title', 'Study Buddhist Dialectics & Epistemology', 'Admissions title', 'shedra'),
('shedra_admit_desc', 'Drodul Phendey Ling Shedra welcomes applications from ordained novice monks, transferred monastic scholars, and lay devotees seeking deep immersion in Buddhist classical philosophy.', 'Admissions description', 'shedra'),
('shedra_benefit_1', 'Full monastic scholarship, boarding, and meals provided for all enrolled monks', 'Admissions benefit 1', 'shedra'),
('shedra_benefit_2', 'Degrees recognized under Bhutanese Monastic Educational Council', 'Admissions benefit 2', 'shedra'),
('shedra_benefit_3', 'Daily debate practice in traditional stone courtyards', 'Admissions benefit 3', 'shedra'),

-- Dharma Learning & LMS
('learning_hero_eyebrow', 'Open Monastic Dharma Education', 'LMS hero eyebrow', 'learning'),
('learning_hero_tibetan', 'ཆོས་ཀྱི་བཀའ་ཁྲིད།', 'LMS Tibetan script title', 'learning'),
('learning_hero_title', 'Learning & Dharma Video Discourses', 'LMS hero title', 'learning'),
('learning_hero_subtitle', 'Explore authentic Tibetan Buddhist teachings, meditation instructions, and philosophical commentaries presented by our revered Khenpos and resident masters in Bhutan.', 'LMS hero subtitle', 'learning'),
('learning_hero_image', 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80', 'LMS hero background image URL', 'learning'),
('learning_cta_label', 'Explore Shedra Courses', 'LMS CTA button label', 'learning'),
('learning_cta_url', '/shedra', 'LMS CTA button target URL', 'learning'),

-- Wisdom Journal / Blog
('blog_hero_eyebrow', 'Wisdom Gazette', 'Blog hero eyebrow', 'blog'),
('blog_hero_tibetan', '༄༅། །ཆོས་ཀྱི་བགྲོ་གླེང་དང་དྲན་དེབ།', 'Blog Tibetan script title', 'blog'),
('blog_hero_title', 'The Bodhi Path: Sacred Journal & Monastic Chronicles', 'Blog hero title', 'blog'),
('blog_hero_subtitle', 'Spiritual discourses, Buddhist philosophical reflections, and living updates on the Great Druk Wangyel Peace Stupa from Gelephu, Bhutan.', 'Blog hero subtitle', 'blog'),
('blog_hero_image', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1800&q=85', 'Blog hero background image URL', 'blog'),
('blog_cta_label', 'Browse Articles', 'Blog CTA label', 'blog'),
('blog_cta_url', '/blog', 'Blog CTA URL', 'blog'),

-- Ceremonial Gazette & News
('news_hero_eyebrow', 'Ceremonial Gazette', 'News hero eyebrow', 'news'),
('news_hero_tibetan', '༄༅། །དགེ་ལུགས་ཀྱི་མཛད་སྒོ་དང་གསལ་བསྒྲགས།', 'News Tibetan script title', 'news'),
('news_hero_title', 'Auspicious Ceremonies & Dharma Teachings', 'News hero title', 'news'),
('news_hero_subtitle', 'Stay aligned with monthly astrological tsog offerings, peace stupa consecrations, and open discourses by Khenpo Tashi Dorji in Gelephu, Bhutan.', 'News hero subtitle', 'news'),
('news_hero_image', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80', 'News hero background image URL', 'news'),
('news_cta_label', 'Upcoming Pujas', 'News CTA label', 'news'),
('news_cta_url', '/prayer-request', 'News CTA URL', 'news'),

-- Sacred Gallery
('gallery_hero_eyebrow', 'Sacred Photo Archives', 'Gallery hero eyebrow', 'gallery'),
('gallery_hero_tibetan', 'སྐུ་བརྙན་དང་དགོན་པའི་པར་རིས།', 'Gallery Tibetan script title', 'gallery'),
('gallery_hero_title', 'Monastery Photo & Video Gallery', 'Gallery hero title', 'gallery'),
('gallery_hero_subtitle', 'Witness the sacred construction of the Great Druk Wangyel Peace Stupa, Shedra monastic student life, and sacred ceremonies in Gelephu, Bhutan.', 'Gallery hero subtitle', 'gallery'),
('gallery_hero_image', 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80', 'Gallery hero background image URL', 'gallery'),
('gallery_cta_label', 'View High Res Archives', 'Gallery CTA label', 'gallery'),
('gallery_cta_url', '/gallery', 'Gallery CTA URL', 'gallery'),

-- Contact Secretariat
('contact_hero_badge', '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དྲུང་ཡིག་ལས་ཁུངས། • Monastic Secretariat', 'Contact hero Tibetan badge', 'contact'),
('contact_hero_title', 'Connect With Drodul Phendey Ling', 'Contact hero title', 'contact'),
('contact_hero_subtitle', 'Whether inquiring about Shedra admissions, stupa sponsorship, ceremonial pujas, or visiting hours, our monastic secretariat is here to assist you.', 'Contact hero subtitle', 'contact'),
('contact_address', 'Great Druk Wangyel Peace Stupa Complex, Gelephu, Sarpang Dzongkhag, Kingdom of Bhutan', 'Secretariat physical address', 'contact'),
('contact_phone', '+975 17556559', 'Secretariat phone number', 'contact'),
('contact_email', 'contact@drodulphendeyling.org', 'Secretariat email address', 'contact'),
('contact_hours', 'Mon - Sat: 08:00 AM - 05:00 PM BST (Bhutan Standard Time)', 'Secretariat visiting hours', 'contact'),
('contact_hours_weekdays', 'Mon - Sat: 08:00 AM - 05:00 PM BST', 'Secretariat weekday hours', 'contact'),
('contact_hours_sunday', 'Sunday: Closed for Sangha Retreat & Puja', 'Secretariat Sunday notice', 'contact'),
('contact_map_url', 'https://maps.google.com', 'Secretariat Google Maps link', 'contact'),
('contact_seat_name', 'Drodul Phendey Ling Monastic Foundation', 'Secretariat legal seat name', 'contact'),
('contact_seat_address', 'Great Druk Wangyel Peace Stupa Complex, Gelephu, Sarpang Dzongkhag, Bhutan', 'Secretariat legal seat address', 'contact'),
('contact_seat_pobox', 'Post Box # 31101, Gelephu General Post Office', 'Secretariat postal box', 'contact'),
('contact_seat_reg', 'Reg. Religious Trust CRO/BTN/2026/049', 'Secretariat CRO registration line', 'contact'),
('contact_general_email', 'contact@drodulphendeyling.org', 'General inquiries email', 'contact'),
('contact_general_phone', '+975 17556559', 'General inquiries phone', 'contact'),
('contact_abbot_email', 'abbot@drodulphendeyling.org', 'Abbot office email', 'contact'),
('contact_dana_email', 'finance@drodulphendeyling.org', 'Offerings and treasury email', 'contact'),
('contact_visiting_notice', 'Devotees and visitors are cordially welcome to circumambulate the Great Peace Stupa daily between 06:00 AM and 07:00 PM BST. Proper modest attire is respectfully requested.', 'Visiting notice', 'contact'),

-- Offering & Prayer Tracking
('tracking_hero_eyebrow', '༄༅། །རྗེས་འདེད་ལྟ་རྟོགས། • Monastic Treasury Reconciliation Ledger', 'Tracking hero eyebrow', 'tracking'),
('tracking_hero_title', 'Live Offering & Prayer Tracking', 'Tracking hero title', 'tracking'),
('tracking_hero_subtitle', 'Track the real-time status of your sacred Dana offering or prayer request through our multi-step monastic treasury verification, bank statement audit, and Section 80G statutory certification.', 'Tracking hero subtitle', 'tracking'),
('tracking_notice', 'Enter your 12-digit UPI UTR, Bank Transfer Reference, Receipt Number (RC-...), or Tracking ID (TRK-...) to track verification progress.', 'Tracking input helper notice', 'tracking'),

-- Footer & Ashtamangala
('footer_show_ashtamangala', 'true', 'Footer Ashtamangala symbol bar visibility', 'footer'),
('footer_copyright', '© 2026 Drodul Phendey Ling Foundation. All rights reserved. Registered Religious & Charitable Trust, Kingdom of Bhutan.', 'Footer copyright line', 'footer'),
('footer_charity_title', 'Commission for Religious Organizations (CRO) Accredited', 'Footer accreditation heading', 'footer'),
('footer_charity_reg', 'CRO/BTN/2026/049 • Gelephu, Sarpang Dzongkhag, Kingdom of Bhutan', 'Footer CRO reg string', 'footer'),
('footer_description', 'Dedicated to universal peace, authentic Buddha Dharma, and the welfare of all sentient beings through the monumental 108ft Great Druk Wangyel Peace Stupa and Shedra Monastic Academy.', 'Footer monastic mandate', 'footer'),
('footer_tibetan_blessing', 'བཀྲ་ཤིས་བདེ་ལེགས། བྱམས་དང་སྙིང་རྗེས་འགྲོ་བ་ཀུན་ལ་ཕན་བདེ་འབྱུང་བར་ཤོག', 'Footer Tibetan auspicious blessing', 'footer'),
('footer_newsletter_title', 'Receive Sacred Gazette Dispatches', 'Footer newsletter title', 'footer'),
('footer_newsletter_desc', 'Subscribe for monthly monastic blessings, astrological puja dates, and stupa construction reports.', 'Footer newsletter description', 'footer'),
('footer_terms_url', '/about', 'Footer terms link', 'footer'),
('footer_privacy_url', '/about', 'Footer privacy link', 'footer'),
('footer_contact_url', '/contact', 'Footer contact link', 'footer'),

-- Social Media Links
('social_facebook', 'https://facebook.com', 'Facebook page URL', 'social'),
('social_instagram', 'https://instagram.com', 'Instagram profile URL', 'social'),
('social_youtube', 'https://youtube.com', 'YouTube channel URL', 'social'),
('social_twitter', 'https://twitter.com', 'Twitter / X URL', 'social'),
('social_whatsapp', '+97517556559', 'Monastery WhatsApp contact number', 'social')

ON DUPLICATE KEY UPDATE 
  setting_value = IF(setting_value IS NULL OR setting_value = '', VALUES(setting_value), setting_value),
  description = IF(description IS NULL OR description = '', VALUES(description), description),
  group_name = IF(group_name IS NULL OR group_name = '', VALUES(group_name), group_name);
