/**
 * Node CommonJS Default Settings Dictionary
 * Provides complete live default site settings for backend controllers and seeders.
 */

const DEFAULT_SETTINGS = {
  // 1. BRANDING & GENERAL
  org_name: 'Drodul Phendey Ling Foundation',
  org_tagline: 'Building Peace. Empowering Lives.',
  org_address: 'Great Druk Wangyel Peace Stupa Complex, Gelephu, Sarpang Dzongkhag, Kingdom of Bhutan',
  org_phone: '+975 17556559',
  org_email: 'contact@drodulphendeyling.org',
  site_name: 'Drodul Phendey Ling Foundation',
  site_tagline: 'Building Peace. Empowering Lives.',
  site_tibetan_name: '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པ།',
  tibetan_title: '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པ།',

  // 2. HEADER & ANNOUNCEMENT BAR
  header_announcement: '☸ Welcoming Devotees to the Historic 108ft Great Druk Wangyel Peace Stupa • 80G Tax Exemption Available',
  header_announcement_on: 'true',
  header_announcement_link: '/about',
  header_phone: '+975 17556559',
  header_email: 'contact@drodulphendeyling.org',
  header_location: 'Gelephu, Sarpang, Bhutan',
  header_cta_label: 'Offer Dana',
  header_cta_link: '/donate',
  header_cta_on: 'true',
  header_btn_text: 'Offer Dana',
  header_btn_link: '/donate',

  // 3. HOMEPAGE: HERO BANNER
  home_hero_badge: '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པ། • Gelephu, Bhutan',
  home_hero_title: 'BUILDING A SACRED LEGACY OF PEACE & WISDOM',
  home_hero_subtitle: 'Constructing the monumental 108ft Great Druk Wangyel Peace Stupa, expanding the Shedra Monastic University, and preserving authentic Buddha Dharma for global harmony in Gelephu, Bhutan.',
  home_hero_image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1800&q=85',
  home_hero_cta_text: 'OFFER DANA / DONATE',
  home_hero_cta_link: '/donate',
  home_hero_cta2_text: 'Explore Stupa Vision',
  home_hero_cta2_link: '/about',

  // 4. HOMEPAGE: IMPACT STATS RIBBON
  stat1_num: '108 Ft',
  stat1_label: 'Monumental Stupa',
  stat1_sub: 'Gelephu, Bhutan',
  stat2_num: '350+',
  stat2_label: 'Monastic Scholars',
  stat2_sub: 'Shedra university scholars',
  stat3_num: '100k+',
  stat3_label: 'Consecrated Prayers',
  stat3_sub: 'Sacred butter lamps',
  stat4_num: '40+',
  stat4_label: 'Global Patronage',
  stat4_sub: 'International devotees',

  // 5. HOMEPAGE: ACTIVE CAMPAIGNS SECTION
  campaigns_badge: 'Sacred Giving Initiatives',
  campaigns_title: 'Support Our Active Monastic Projects',
  campaigns_subtitle: 'Every contribution directly funds the 108ft Great Peace Stupa, provides meals and education for 350+ monks, and preserves living Buddha Dharma.',
  campaigns_cta_text: 'View All Giving Causes',
  campaigns_cta_link: '/donate',

  // 6. HOMEPAGE: DOCUMENTARY FILM SECTION
  doc_badge: 'Monastery Documentary Film',
  home_doc_badge: 'Monastery Documentary Film',
  home_doc_title: 'The Sacred Legacy of Drodul Phendey Ling',
  doc_video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  home_doc_video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  doc_poster_image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80',
  home_doc_desc: 'Journey into the spiritual heart of Gelephu, Bhutan. Witness the devotion of our monastic community, the architectural wonder of the 108ft Peace Stupa, and the living wisdom of Tibetan Buddhism.',
  doc_duration: '14 min documentary',
  doc_cta1_text: 'Watch Full Story',
  doc_cta2_text: 'About Our Lineage',

  // 7. HOMEPAGE: 4 SACRED PILLARS
  home_pillars_badge: 'Four Sacred Pillars of Activity',
  home_pillars_title: 'Fulfilling the Bodhisattva Mandate',
  home_pillars_subtitle: 'Preserving Buddhist heritage through architectural monuments, philosophical inquiry, unbroken prayer dedications, and humanitarian sangha care.',
  home_pillar1_title: '108ft Great Peace Stupa',
  home_pillar1_badge: 'Architectural Stupa',
  home_pillar1_desc: 'Constructing a landmark symbol of peace with 108 stone-carved prayer wheels and consecration relics.',
  home_pillar2_title: 'Shedra Monastic University',
  home_pillar2_badge: '9-Year Acharya',
  home_pillar2_desc: 'Educating 350+ young monks in Buddhist philosophy, classical debate, linguistics, and Dharma meditation.',
  home_pillar3_title: 'Sacred Puja & Butter Lamps',
  home_pillar3_badge: 'Daily Consecration',
  home_pillar3_desc: 'Perpetual prayers dedicated by resident monks for obstacle clearance, longevity, and world peace.',
  home_pillar4_title: 'Humanitarian Relief & Care',
  home_pillar4_badge: 'Sangha Care',
  home_pillar4_desc: 'Providing daily vegetarian nutrition, medical treatment, robes, and community welfare across Gelephu.',

  // 8. HOMEPAGE: PRAYER & BUTTER LAMP CALLOUT
  home_prayers_badge: 'Consecrated Evening Rituals',
  home_prayers_title: 'Request Sacred Prayers & 108 Butter Lamps',
  home_prayers_subtitle: 'Submit personal prayer intentions and names of loved ones. Our resident Shedra monks chant consecrated prayers and illuminate 108 brass butter lamps in the holy shrine altar.',
  home_prayers_cta_text: 'Light a Butter Lamp',
  home_prayers_cta_link: '/prayer-request',

  // 9. HOMEPAGE: ABOUT NARRATIVE
  home_about_title: 'From Sacred Lineage to Global World Peace',
  home_about_description: 'Nestled in the tranquil Himalayan foothills of Gelephu, Bhutan, Drodul Phendey Ling Foundation brings together revered Buddhist masters, dedicated monk scholars, and international patrons to preserve centuries-old Tibetan Buddhist heritage and complete the historic Great Druk Wangyel Peace Stupa.',

  // 10. ABOUT US PAGE
  about_tibetan_eyebrow: '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དགོན་པའི་ལོ་རྒྱུས། • Sacred Monastic Heritage',
  about_page_title: 'About Drodul Phendey Ling Foundation',
  about_page_subtitle: 'Established in the tranquil Himalayan foothills of Gelephu, Sarpang Dzongkhag, Bhutan, to nurture authentic Buddha Dharma, train monk scholars, and build the historic 108ft Great Druk Wangyel Peace Stupa.',
  about_mandate_text: 'Founded under the spiritual patronage of venerable masters, our monastery serves as a beacon of Vajrayana wisdom, sheltering over 350 monks and leading humanitarian projects.',
  about_pillars_tibetan: 'རྩ་བའི་དམིགས་ཡུལ་གསུམ།',
  about_pillars_title: 'Three Sacred Core Pillars',
  about_pillars_intro: 'Our monastery guides activities through three noble focal points: authentic lineage preservation, rigorous monastic education, and compassionate humanitarian welfare.',
  about_pillar_1_title: 'Sacred Lineage & Vision',
  about_pillar_1_desc: 'Rooted in authentic Vajrayana and Mahayana traditions, our mission is to cultivate universal compassion, wisdom, and an enlightened sanctuary where monastic and lay practitioners realize inner peace.',
  about_pillar_2_title: 'Shedra Monastic University',
  about_pillar_2_desc: 'Providing 350+ enrolled monks with full residential scholarships, classical Tibetan linguistics, Abhidharma, Madhyamaka philosophy, debate epistemics, and contemplative solitary retreats.',
  about_pillar_3_title: 'Great Peace Stupa',
  about_pillar_3_desc: 'The monumental 108-foot Great Druk Wangyel Peace Stupa serves as a beacon of harmony, housing sacred relic chambers, 108 stone-carved prayer wheels, and pacifying discord for all beings.',
  about_leader_pill: 'Monastic Leadership',
  about_leader_heading: 'Venerable Spiritual Guidance',
  about_leader_name: 'H.E. Khenpo Karma Rinpoche',
  about_leader_title: 'Abbot & Principal of Shedra Academy',
  about_leader_bio: 'Having completed nine years of rigorous Shedra curriculum and traditional solitary mountain retreat, Khenpo Rinpoche oversees the monastic training, sacred stupa construction, and philanthropic welfare programs in Gelephu, Bhutan.',
  about_leader_blessing: 'May every stone carved for this Stupa, every mantra chanted in this Shedra, bring peace to a troubled world.',
  about_leader_image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
  about_leader_cta_text: 'Contact Abbot Office',
  about_leader_cta_link: '/contact',
  about_statutory_badge: 'Official Accreditation',
  about_statutory_title: 'Statutory Trust & Accountability',
  about_statutory_desc: 'Drodul Phendey Ling Foundation operates in strict accordance with the Religious Organizations Act of the Kingdom of Bhutan. Our accounts are audited annually by certified independent chartered accountants and submitted to statutory regulatory authorities.',
  about_statutory_summary: 'Registered under the Commission for Religious Organizations (CRO) of Bhutan • Registration No: CRO/BTN/2026/049. All donations are 100% transparent and audited.',
  about_statutory_fcra: 'Approved for institutional cross-border wire transfers and statutory tax certification.',

  // 11. DONATION & BANK WIRE DETAILS
  donate_hero_title: 'Make A Meritorious Offering for Peace & Buddha Dharma',
  donate_hero_subtitle: 'Every offering directly finances the 108ft Great Druk Wangyel Peace Stupa, sustains resident monks with nutrition and education, and radiates blessings of merit across the world.',
  donate_hero_badge: 'Charitable Giving • 80G Tax Exemption Available',
  donate_hero_image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
  donate_bank_title: 'Direct Bank Transfer / Wire Details',
  donate_bank_subtitle: 'Devotees preferring direct RTGS, NEFT, or international SWIFT wire transfers may remit directly to our official institutional account:',
  bank_name: 'Bank of Bhutan Ltd. (BoB)',
  bank_account_name: 'Drodul Phendey Ling Foundation',
  bank_account_no: '200847291038',
  bank_swift_code: 'BHUBBTBT',
  bank_branch: 'Gelephu Main Branch, Bhutan',
  bank_ifsc: 'BOBB0000001',
  bank_upi_id: 'drodulphendeyling@bob',
  bank_qr_image: '',
  upi_merchant_vpa: 'drodulphendeyling@bob',
  upi_merchant_name: 'Drodul Phendey Ling Foundation',
  donation_preset_amounts: '500, 1100, 2100, 5100, 11000',
  donation_default_amount: '1100',
  donate_presets_title: 'Sacred Offering Presets',
  donate_presets_subtitle: 'Choose an auspicious offering amount. Each tier supports monastic essentials, ritual butter lamps, and stupa construction.',
  donate_presets_merit_note: 'Custom amounts are welcome. 80G tax receipt is issued automatically upon verification.',
  donate_tier_1_amount: '500',
  donate_tier_1_label: '21 Butter Lamps Puja',
  donate_tier_2_amount: '1100',
  donate_tier_2_label: 'Daily Sangha Nutrition Fund',
  donate_tier_3_amount: '2100',
  donate_tier_3_label: 'Monastic Robes & Healthcare',
  donate_tier_4_amount: '5100',
  donate_tier_4_label: 'Shedra Study Scholarships',
  donate_tier_5_amount: '11000',
  donate_tier_5_label: 'Peace Stupa Carved Stone',

  // 12. STATUTORY TAX & EXEMPTION DISCLOSURES
  tax_exempt_title: 'Statutory Tax Exemption & Monastic Governance',
  tax_exempt_reg: 'DPL/TAX-EXEMPT/BTN/2026/80G-092',
  tax_80g_order_no: 'CIT(E)/THIMPHU/80G/2026-27/AAATD1234F',
  tax_exempt_authority: 'Commission for Religious Organizations (CRO), Kingdom of Bhutan',
  tax_exempt_clause: 'Section 80G Tax Deductible Charitable Contribution',
  tax_exempt_percent: '100% Tax Deductible in Bhutan',
  tax_exempt_timeline: 'Certified PDF money receipt issued immediately upon treasury verification.',
  tax_exempt_email: 'finance@drodulphendeyling.org',

  // 13. CEREMONIAL PRAYERS & BUTTER LAMPS PAGE
  prayer_tibetan_eyebrow: '༄༅། །མར་མེ་སྨོན་ལམ། • Consecrated Sangha Pujas & Butter Lamps',
  prayer_hero_title: 'Sacred Prayer Dedication & Offerings',
  prayer_hero_subtitle: 'Our resident monastic Sangha at Drodul Phendey Ling recites daily consecrated prayers and illuminates brass butter lamps before the holy altar for world peace, health, longevity, and obstacle clearance.',
  prayer_puja_heading: 'Daily Consecrated Monastic Pujas',
  prayer_puja_1_title: 'Grand Tara Obstacle Clearance Puja (Drolma Chodpa)',
  prayer_puja_1_desc: 'Chanting the 21 Praises to Tara for swift protection, spiritual clarity, and pacification of worldly difficulties.',
  prayer_puja_2_title: 'Medicine Buddha Healing Puja (Menlha)',
  prayer_puja_2_desc: 'Consecrated healing visualization and recitations dedicated to those experiencing illness, physical suffering, or surgery.',
  prayer_lamp_badge: 'Perpetual Light Offering',
  prayer_lamp_title: '108 Sacred Butter Lamp Illuminations',
  prayer_tier_1_count: '21',
  prayer_tier_1_amt: '500',
  prayer_tier_2_count: '108',
  prayer_tier_2_amt: '1500',
  prayer_schedule_title: 'Monastery Puja & Chanting Schedule',
  prayer_schedule_desc: 'Our Sangha adheres to the ancient liturgical cycle with three consecrated recitation periods daily:',
  prayer_schedule_morning: '05:30 AM - 07:00 AM (Dawn Tara & Sang Offering)',
  prayer_schedule_evening: '05:30 PM - 07:00 PM (Dusk Mahakala & Dharmapala Protector Ritual)',
  prayer_session_1_title: 'Dawn Tara Puja (Drolma Chodpa)',
  prayer_session_1_time: '05:30 AM - 07:00 AM',
  prayer_session_1_desc: 'Praising the 21 Taras for swift obstacle clearance, feminine wisdom, and family well-being.',
  prayer_session_2_title: 'Noon Medicine Buddha Healing Puja',
  prayer_session_2_time: '11:00 AM - 12:30 PM',
  prayer_session_2_desc: 'Consecrated chanting for recovery from illness, mental pacification, and compassionate healing.',
  prayer_session_3_title: 'Dusk Mahakala & Dharmapala Protector Ritual',
  prayer_session_3_time: '05:30 PM - 07:00 PM',
  prayer_session_3_desc: 'Dharmapala invocation and 108 butter lamp illuminations to dispel negative conditions and safeguard peace.',

  // 14. SHEDRA MONASTIC ACADEMY PAGE
  shedra_hero_badge: 'Center for Advanced Buddhist Epistemology & Scholastic Studies',
  shedra_hero_title: 'Drodul Phendey Ling Shedra Monastic Academy',
  shedra_hero_subtitle: 'Rooted in the ancient Nalanda scholastic lineage of Bhutan, our Shedra trains monk scholars in the Five Great Treatises of Buddhist Philosophy over a rigorous 9-year Master of Buddhist Studies (Acharya) curriculum.',
  shedra_hero_image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80',
  shedra_shastras_badge: 'Scholastic Heritage',
  shedra_shastras_title: 'The Five Great Shastras',
  shedra_shastras_subtitle: 'Every monk scholar must master debate, textual translation, and meditation upon the five comprehensive pillars of classical Indian and Tibetan Buddhism.',
  shastra1_title: 'Pramanavarttika (Buddhist Epistemology & Logic)',
  shastra1_years: 'Years 1 - 2',
  shastra1_desc: 'Dharmakirti’s profound treatise on validity, reasoning, perception, and philosophical debate.',
  shastra2_title: 'Prajnaparamita (Perfection of Wisdom)',
  shastra2_years: 'Years 3 - 4',
  shastra2_desc: 'Maitreya and Asanga’s Abhisamayalankara exploring the stages and grounds of the Bodhisattva path.',
  shedra_fac_title: 'Monastic Study Facilities & Campus',
  shedra_fac_desc: 'Purpose-built Dharma classrooms, traditional open-air debate stone courtyards, extensive scripture library, and monk residential quarters in Gelephu.',
  shedra_fac_1_title: 'Debate Courtyard (Chora)',
  shedra_fac_1_desc: 'Daily afternoon and evening dialectical debates cultivating sharp analytical mind and scriptural mastery.',
  shedra_fac_2_title: 'Sacred Kangyur & Tengyur Library',
  shedra_fac_2_desc: 'Housing over 300 volumes of canonical Buddhist treatises and classical Tibetan block prints.',
  shedra_admit_pill: 'Join the Academy',
  shedra_admit_title: 'Study Buddhist Dialectics & Epistemology',
  shedra_admit_desc: 'Drodul Phendey Ling Shedra welcomes applications from ordained novice monks, transferred monastic scholars, and lay devotees seeking deep immersion in Buddhist classical philosophy.',
  shedra_benefit_1: 'Full monastic scholarship, boarding, and meals provided for all enrolled monks',
  shedra_benefit_2: 'Degrees recognized under Bhutanese Monastic Educational Council',
  shedra_benefit_3: 'Daily debate practice in traditional stone courtyards',

  // 15. DHARMA LEARNING & LMS PAGE
  learning_hero_eyebrow: 'Open Monastic Dharma Education',
  learning_hero_tibetan: 'ཆོས་ཀྱི་བཀའ་ཁྲིད།',
  learning_hero_title: 'Learning & Dharma Video Discourses',
  learning_hero_subtitle: 'Explore authentic Tibetan Buddhist teachings, meditation instructions, and philosophical commentaries presented by our revered Khenpos and resident masters in Bhutan.',
  learning_hero_image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80',
  learning_cta_label: 'Explore Shedra Courses',
  learning_cta_url: '/shedra',

  // 16. WISDOM JOURNAL & BLOG PAGE
  blog_hero_eyebrow: 'Wisdom Gazette',
  blog_hero_tibetan: '༄༅། །ཆོས་ཀྱི་བགྲོ་གླེང་དང་དྲན་དེབ།',
  blog_hero_title: 'The Bodhi Path: Sacred Journal & Monastic Chronicles',
  blog_hero_subtitle: 'Spiritual discourses, Buddhist philosophical reflections, and living updates on the Great Druk Wangyel Peace Stupa from Gelephu, Bhutan.',
  blog_hero_image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1800&q=85',
  blog_cta_label: 'Browse Articles',
  blog_cta_url: '/blog',

  // 17. CEREMONIAL GAZETTE & NEWS EVENTS PAGE
  news_hero_eyebrow: 'Ceremonial Gazette',
  news_hero_tibetan: '༄༅། །དགེ་ལུགས་ཀྱི་མཛད་སྒོ་དང་གསལ་བསྒྲགས།',
  news_hero_title: 'Auspicious Ceremonies & Dharma Teachings',
  news_hero_subtitle: 'Stay aligned with monthly astrological tsog offerings, peace stupa consecrations, and open discourses by Khenpo Tashi Dorji in Gelephu, Bhutan.',
  news_hero_image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
  news_cta_label: 'Upcoming Pujas',
  news_cta_url: '/prayer-request',

  // 18. SACRED PHOTO & VIDEO GALLERY PAGE
  gallery_hero_eyebrow: 'Sacred Photo Archives',
  gallery_hero_tibetan: 'སྐུ་བརྙན་དང་དགོན་པའི་པར་རིས།',
  gallery_hero_title: 'Monastery Photo & Video Gallery',
  gallery_hero_subtitle: 'Witness the sacred construction of the Great Druk Wangyel Peace Stupa, Shedra monastic student life, and sacred ceremonies in Gelephu, Bhutan.',
  gallery_hero_image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1400&q=80',
  gallery_cta_label: 'View High Res Archives',
  gallery_cta_url: '/gallery',

  // 19. CONTACT SECRETARIAT PAGE
  contact_hero_badge: '༄༅། །དྲོ་བདུལ་ཕན་བདེ་གླིང་དྲུང་ཡིག་ལས་ཁུངས། • Monastic Secretariat',
  contact_hero_title: 'Connect With Drodul Phendey Ling',
  contact_hero_subtitle: 'Whether inquiring about Shedra admissions, stupa sponsorship, ceremonial pujas, or visiting hours, our monastic secretariat is here to assist you.',
  contact_address: 'Great Druk Wangyel Peace Stupa Complex, Gelephu, Sarpang Dzongkhag, Kingdom of Bhutan',
  contact_phone: '+975 17556559',
  contact_email: 'contact@drodulphendeyling.org',
  contact_hours: 'Mon - Sat: 08:00 AM - 05:00 PM BST (Bhutan Standard Time)',
  contact_hours_weekdays: 'Mon - Sat: 08:00 AM - 05:00 PM BST',
  contact_hours_sunday: 'Sunday: Closed for Sangha Retreat & Puja',
  contact_map_url: 'https://maps.google.com',
  contact_seat_name: 'Drodul Phendey Ling Monastic Foundation',
  contact_seat_address: 'Great Druk Wangyel Peace Stupa Complex, Gelephu, Sarpang Dzongkhag, Bhutan',
  contact_seat_pobox: 'Post Box # 31101, Gelephu General Post Office',
  contact_seat_reg: 'Reg. Religious Trust CRO/BTN/2026/049',
  contact_general_email: 'contact@drodulphendeyling.org',
  contact_general_phone: '+975 17556559',
  contact_abbot_email: 'abbot@drodulphendeyling.org',
  contact_dana_email: 'finance@drodulphendeyling.org',
  contact_visiting_notice: 'Devotees and visitors are cordially welcome to circumambulate the Great Peace Stupa daily between 06:00 AM and 07:00 PM BST. Proper modest attire is respectfully requested.',

  // 20. OFFERING & PRAYER TRACKING PAGE
  tracking_hero_eyebrow: '༄༅། །རྗེས་འདེད་ལྟ་རྟོགས། • Monastic Treasury Reconciliation Ledger',
  tracking_hero_title: 'Live Offering & Prayer Tracking',
  tracking_hero_subtitle: 'Track the real-time status of your sacred Dana offering or prayer request through our multi-step monastic treasury verification, bank statement audit, and Section 80G statutory certification.',
  tracking_notice: 'Enter your 12-digit UPI UTR, Bank Transfer Reference, Receipt Number (RC-...), or Tracking ID (TRK-...) to track verification progress.',

  // 21. FOOTER & ASHTAMANGALA
  footer_show_ashtamangala: 'true',
  footer_copyright: '© 2026 Drodul Phendey Ling Foundation. All rights reserved. Registered Religious & Charitable Trust, Kingdom of Bhutan.',
  footer_charity_title: 'Commission for Religious Organizations (CRO) Accredited',
  footer_charity_reg: 'CRO/BTN/2026/049 • Gelephu, Sarpang Dzongkhag, Kingdom of Bhutan',
  footer_description: 'Dedicated to universal peace, authentic Buddha Dharma, and the welfare of all sentient beings through the monumental 108ft Great Druk Wangyel Peace Stupa and Shedra Monastic Academy.',
  footer_tibetan_blessing: 'བཀྲ་ཤིས་བདེ་ལེགས། བྱམས་དང་སྙིང་རྗེས་འགྲོ་བ་ཀུན་ལ་ཕན་བདེ་འབྱུང་བར་ཤོག',
  footer_newsletter_title: 'Receive Sacred Gazette Dispatches',
  footer_newsletter_desc: 'Subscribe for monthly monastic blessings, astrological puja dates, and stupa construction reports.',
  footer_terms_url: '/about',
  footer_privacy_url: '/about',
  footer_contact_url: '/contact',

  // 22. SOCIAL MEDIA CHANNELS
  social_facebook: 'https://facebook.com',
  social_instagram: 'https://instagram.com',
  social_youtube: 'https://youtube.com',
  social_twitter: 'https://twitter.com',
  social_whatsapp: '+97517556559'
};

module.exports = DEFAULT_SETTINGS;
module.exports.DEFAULT_SETTINGS = DEFAULT_SETTINGS;
